on:
  pull_request:
    branches:
      - main
      - master
      - development
  push:
    branches:
      - main
      - master
      - development
    paths:
      - .github/workflows/render-validation-rmd.yaml
      - R/SpaDES/global.Rmd

name: Render validation Rmd

jobs:
  render:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    name: Render validation Rmd
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rmarkdown
            any::knitr
            any::bookdown

      - name: Install SpaDES packages
        run: |
          install.packages("SpaDES", dependencies = TRUE)
          remotes::install_github("PredictiveEcology/SpaDES.docs@development")
        shell: Rscript {0}

      - name: Install module package dependencies
        run: |
          mods <- dir("R/SpaDES/m")
          pkgs <- sapply(mods, function(m) SpaDES.core::packages(modules = m, paths = "R/SpaDES/m"))
          pkgs <- unique(unlist(pkgs))
          Require::Require(pkgs)
        shell: Rscript {0}

      - name: Render validation Rmd
        run: |
          rmarkdown::render("R/SpaDES/global.Rmd", encoding = "UTF-8", output_dir = "R/SpaDES")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit R/SpaDES/global.html -m 'Re-build R/SpaDES/global.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}} || echo "No changes to commit"
