on:
  pull_request:
    branches:
      - main
      - master
      - development
  push:
    branches:
      - main
      - master
      - development
    paths:
      - .github/workflows/render-validation-rmd.yaml
      - R/SpaDES/global.Rmd

name: Render validation Rmd

jobs:
  render:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    name: Render validation Rmd
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      - name: Install additional system dependencies
        run: |
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libgdal-dev \
            libgeos-dev \
            libgit2-dev \
            libglpk-dev \
            libmagick++-dev \
            libproj-dev \
            libudunits2-dev \
            libxml2-dev \
            python3-gdal

      - name: Set R library
        run: |
          pkgPath <- file.path("packages", version$platform, paste0(version$major, ".", strsplit(version$minor, "[.]")[[1]][1]))
          dir.create(dirname(pkgPath), recursive = TRUE)
          file.symlink(Sys.getenv("R_LIBS_USER"), pkgPath)
        shell: Rscript {0}

      - uses: PredictiveEcology/actions/install-Require@v0
        with:
          GitTag: '8ac756d66bc145f226f39e703e3787d3aed159f2'

      - uses: PredictiveEcology/actions/install-Rmd-pkgs@v0

      - uses: PredictiveEcology/actions/install-SpaDES@v0

      - name: Install additional packages
        run: |
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/focal/latest", CRAN = "https://cran.rstudio.com"))
          Require::Require(c("LandR", "ggspatial", "ggpubr", "cowplot", "DiagrammeR"))
        shell: Rscript {0}

      - name: Render validation Rmd
        run: |
          rmarkdown::render("R/SpaDES/global.Rmd", encoding = "UTF-8", output_dir = "R/SpaDES", knit_root_dir = getwd())
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit R/SpaDES/global.html -m 'Re-build R/SpaDES/global.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}} || echo "No changes to commit"
